spring:
  application:
    name: smart_devices
    
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=laptop_store;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123456
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update 
     
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 175075082752-ov91fapo4j0m4ktr9cvpgve1l8nr99me.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 7592302570834708
            client-secret: 456879b47b7a3a6bc12b22fb1a72c1d1
            scope:
              - email
              - public_profile
              
  mail:
    host: smtp.gmail.com
    port: 587
    username: tinhnthps30150@fpt.edu.vn
    password: eyqmautkudpvamfo
    properties:
     mail:
       smtp: 
         auth: true
         starttls: 
           enable: true

cloudinary:
  cloud-name: dxowhxfwj
  api-key: 493466681247413
  api-secret: QXjt9-bbjJK_TDjpZsoLJsAQ2Rk